### ISSUE TITLE
这个生成出来的diff和 http://php.net/manual/zh/book.xdiff.php 数据一致吗？

### ISSUE THREAD

**Issue by boboweb** [eaglewu/phpdiff#1]
官方也有一个diff工具，http://php.net/manual/zh/function.xdiff-file-bdiff.php，通过这个函数生成的diff数据和phpdiff还有bsdiff数据是一致的吗？

**Comment by wudi** [comment]
@boboweb  不一致！
您提供的官方 xdiff 扩展是 依赖 [LibXDiff](http://www.xmailserver.org/xdiff-lib.html) 库 。
这个 phpdiff 是依赖于 [bsdiff](http://www.daemonology.net/bsdiff/) 因为 bsdiff 在安卓上可以很方便的使用，本项目初衷是为安卓生成差异包。
所以两者不可混用。
:)

**Comment by boboweb** [comment]
哈哈，太好了，我就要这个功能。看来是搞安卓的同行啊，请问是在哪家公司？：）

**Comment by wudi** [comment]
我是写后端的 PHP 方向

**Comment by luchongkang** [comment]
@eaglewu 你好，我们项目最近正好有这个需求，想用PHP为客户端文件生成补丁包的，请问你们是用什么第三方工具包或者是PHP原生函数的？

**Comment by wudi** [comment]
就是这个PHP扩展，其实就是封装了 `bsdiff` 的两个函数。

**Comment by luchongkang** [comment]
@boboweb 貌似Windows没有这个扩展，一直在找。

**Comment by wudi** [comment]
@boboweb  不支持 windows
你可以尝试 直接调用 `bsdiff` 命令处理.
