### ISSUE TITLE
问题—— ./configure: No such file or directory

### ISSUE THREAD

**Issue by hanleirx** [eaglewu/phpdiff#2]
你好，我在执行这一句的时候（./configure --with-php-config=/php-path/bin/php-config）会报错（-bash: ./configure: No such file or directory），这是为什么啊？

**Comment by eaglewu** [comment]
执行 ./configure 之前要执行

**Comment by wudi** [comment]
执行 `./configure` 之前要执行  `/php-path/bin/phpize` 命令
