### ISSUE TITLE
php5.3.6环境，编译和使用都会出现问题

### ISSUE THREAD

**Issue by itbirds** [eaglewu/phpdiff#3]
你好，
       在一个项目中使用，phpdiff这个扩展，编译的时候会报错，报错内容是
     `**/usr/local/src/phpdiff/phpdiff.c:75: error: ‘PHP_FE_END’ undeclared here (not in a function)**`
      这个问题，我自己修改解决了，不过在使用的时候，出现了一个新的问题
`**[pool www] child 25734 said into stderr: "php-fpm: pool www: symbol lookup error:    /usr/local/php/ext/phpdiff.so: undefined symbol: BZ2_bzWriteOpen**`
我看了，你的源文件，phpdiff.c的483，596，623行使用了这个函数。个人认为可能是bz2的扩展的问题。
  请你帮忙看看，非常感谢！

**Comment by wudi** [comment]
编译扩展时设置 LDFLAGS 环境变量 引入 bz2 链接库

``` sh
$ phpize

# LDLIBS用来指明需要的链接库 （必须已经安装过 bzip2 包。参考 yum install bzip2 bzip2-devel）
$ export LDFLAGS="-lbz2" && ./configure
```

**Comment by wudi** [comment]
有其他问题可继续提问，这个 Issue 我先关闭了
